### ISSUE TITLE
Removed methods in SW 5.4

### ISSUE THREAD

**Issue by mmachatschek** [findologic/plugin-shopware-5-api#100]
Currently there are methods in use to check if the shop has a secure connection or not for exporting the correct urls with the `http` or `https` protocol.

Like `getAlwaysSecure()` or `getSecureBasePath()`

Since these methods where removed with the new Shopware Release 5.4, these methods should not be used anymore.

See https://github.com/shopware/shopware/blob/5.4/UPGRADE-5.4.md#removals-1 for more information

**Comment by jovanp-soprex** [comment]
Hi guys,

we will proceed with this issue fix and keep you updated!

Regards,
Jovan
